version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: thai_glocal_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thai_glocal
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./server
    container_name: thai_glocal_backend
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

  webclient:
    build: ./webclient
    container_name: thai_glocal_webclient
    ports:
      - "8080:8080"
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: thai_glocal_frontend
    ports:
      - "5173:5173"
    depends_on:
      - webclient